
#Here are configs that need reloading to take effect
[general]
	#Enable Creative Tab
	creative_tab = false
	#Set to false to disable custom dispenser behaviors (i.e: filling jars) if for some reason they are causing trouble
	dispensers = true
	#Creates a creative tab full of filled jars
	jar_tab = false
	#Enables custom Configured config screen
	custom_configured_screen = true
	#Save generated resources to disk in a 'debug' folder in your game directory. Mainly for debug purposes but can be used to generate assets in all wood types for your mods :0
	debug_save_dynamic_pack = false

[blocks]
	planter = false
	clock_block = true
	pedestal = true
	wind_vane = true
	redstone_illuminator = false
	notice_board = true
	crank = true
	jar = false
	faucet = false
	turn_table = true
	spring_launcher = true
	speaker_block = true
	sign_post = true
	hanging_sign = true
	bellows = false
	sconce = true
	sconce_green = false
	cage = true
	item_shelf = true
	sconce_lever = true
	cog_block = true
	globe = true
	hourglass = true
	sack = false
	blackboard = true
	safe = true
	copper_lantern = false
	gold_trapdoor = false
	gold_door = false
	bamboo_spikes = true
	bamboo_spikes_tipped = false
	stone_lamp = false
	end_stone_lamp = false
	blackstone_lamp = false
	deepslate_lamp = false
	checker_block = false
	netherite_door = false
	netherite_trapdoor = false
	lock_block = true
	flax = false
	rope = true
	pulley_block = true
	fodder = false
	crimson_lantern = false
	magma_cream_block = false
	daub = false
	wattle_and_daub = false
	timber_frame = false
	flag = true
	stone_tile = false
	goblet = false
	raked_gravel = false
	statue = true
	iron_gate = true
	feather_block = true
	flint_block = false
	urn = true
	ash = true
	ash_bricks = false
	doormat = true
	flower_box = false
	blackstone_tile = false
	globe_sepia = true
	present = true
	silver_trapdoor = false
	silver_door = false
	lead_trapdoor = false
	lead_door = false
	sugar_cube = true
	lapis_bricks = false
	relayer = true
	crystal_display = true
	candle_holder = true

[items]
	flute = true
	stasis = false
	dispenser_minecart = true
	soap = false
	bubble_blower = true
	antique_ink = false
	shulker_shell = false
	candy = false
	wrench = true
	slingshot = true
	rope_arrow = true
	bomb = false
	pancake = false
	quiver = true

